# 激活actuator 部分端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thyme?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.208.102
    port: 29638
    password: ahhx@9637
    timeout: 5000