# 激活actuator 部分端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://106.13.103.1:3306/thyme?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Trading@it1851
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.38.128
    port: 6379
    #password: UcJyWk6GEKUx6p6V
    #timeout: 5000
logging:
  config: classpath:log4j2/log4j2-spring-dev.xml
