server:
  servlet:
    context-path: /thyme
  port: 8600
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  # thymeleaf配置
  thymeleaf:
    cache: false
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false
#登录图形验证码有效时间(单位分钟)/宽度/高度/位数
loginCode:
  expiration: 2
  width: 111
  height: 36
  digit: 2