server:
  servlet:
    context-path: /thyme
  port: 8500
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  # thymeleaf配置
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false
